runtime: python38

env_variables:
        CLOUD_SQL_USERNAME: marketmaster
        CLOUD_SQL_PASSWORD: columbia
        CLOUD_SQL_DATABASE_NAME: marketdb1
        CLOUD_SQL_CONNECTION_NAME: coused:us-central1:cumarket-db
